[workspace]
resolver = "2"
members = [
    # Common
    "common",

    # Controller
    "controller",

    # Drivers
    "drivers/pterodactyl",

    # Clients
    "cli",
    "clients/wrapper",
]

[workspace.metadata]
protocol-version = 4

[profile.release]
lto = true
strip = true
