description = "Minecraft is a game about placing blocks and going on adventures. Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in Creative Mode with unlimited resources or mine deep in Survival Mode, crafting weapons and armor to fend off dangerous mobs. Do all this alone or with friends."
version = "0.1.0"
authors = ["HttpRafa"]

exclusions = ["template.toml", "prepare/"]

shutdown = "stop"

[environment]
VERSION = "latest"
SERVER_JARFILE = "server.jar"
TRANSFER_COMMAND = "transfer %HOST% %PORT% %NAME%"
STARTED_REGEX = "Done \\([0-9]+\\.[0-9]+s\\)! For help, type \"help\""
STOPPING_REGEX = "Stopping the server"
USER_CONNECTED_REGEX = "UUID of player ([a-zA-Z0-9_-]+) is ([a-zA-Z0-9_-]+)"
USER_DISCONNECTED_REGEX = "([a-zA-Z0-9_-]+) lost connection"
RUST_BACKTRACE = "1"

[prepare.unix]
command = "bash"
args = ["-c", "chmod +x prepare/unix.sh && ./prepare/unix.sh"]

[prepare.windows]
command = "powershell.exe"
args = ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "prepare/windows.ps1"]

[startup.unix]
command = "bash"
args = ["-c", "chmod +x startup/unix.sh && ./startup/unix.sh"]

[startup.windows]
command = "powershell.exe"
args = ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "startup/windows.ps1"]