[package]
name = "cli"
version = "0.0.0-nightly"
edition = "2021"

[dependencies]
# Common
common = { path = "../common" }

# Logging
simplelog = { version = "0.12.2", features = ["paris"] }
loading = "0.4.0"

# File management
dirs = "6.0.0"

# Input parsing
inquire = { version = "0.7.5", features = ["editor"] }
rustyline = "15.0.0"

# Error handling
anyhow = "1.0.97"

# Command line arguments
clap = { version = "4.5.32", features = ["derive"] }

# Configuration
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"

# Async runtime
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "fs", "macros"] }
futures = "0.3.31"

# Network
url = { version = "2.5.4", features = ["serde"] }
prost = "0.13.5"
tonic = { version = "0.13.0", features = ["tls", "tls-native-roots"] }

[build-dependencies]
toml = "0.8.20"
tonic-build = "0.13.0"