[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# Common
common = { path = "../common" }

# Logging
log = "0.4.22"
simplelog = "0.12.2"
colored = "2.1.0"

# File management
dirs = "5.0.1"

# Input parsing
inquire = "0.7.5"

# Error handling
anyhow = "1.0.93"

# Command line arguments
clap = { version = "4.5.21", features = ["derive"] }

# Configuration
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

# Async runtime
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }

# API
url = "2.5.4"
prost = "0.13.3"
tonic = "0.12.3"

[build-dependencies]
toml = "0.8.19"
tonic-build = "0.12.3"