[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# Common
common = { path = "../common" }

# Logging
log = "0.4.22"
simplelog = "0.12.2"
colored = "2.1.0"

# Input parsing
inquire = "0.7.5"

# Error handling
anyhow = "1.0.86"

# Async runtime
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "macros"] }

# API
url = "2.5.2"
prost = "0.13.1"
tonic = "0.12.1"

[build-dependencies]
toml = "0.8.16"
tonic-build = "0.12.1"