[package]
name = "cli"
version = "0.0.0-nightly"
edition = "2021"

[dependencies]
# Common
common = { path = "../common" }

# Terminal
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.29.0"
tui-textarea = "0.7.0"

# File management
directories = "6.0.0"

# Error handling
color-eyre = "0.6.3"

# Configuration
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
base64 = "0.22.1"

# Async runtime
tokio-stream = "0.1.17"
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "fs", "macros"] }
futures = "0.3.31"

# Network
url = { version = "2.5.4", features = ["serde"] }
rustls = { version = "0.23.26", default-features = false, features = ["ring"] }
sha2 = "0.10.8"
prost = "0.13.5"
tonic = { version = "0.13.0", features = ["tls-ring"] }

[build-dependencies]
toml = "0.8.20"
tonic-build = "0.13.0"