[package]
name = "cli"
version = "0.0.0-nightly"
edition = "2021"

[dependencies]
# Common
common = { path = "../common" }

# Logging
simplelog = { version = "0.12.2", features = ["paris"] }
loading = "0.4.0"

# File management
dirs = "6.0.0"

# Input parsing
inquire = "0.7.5"

# Error handling
anyhow = "1.0.95"

# Command line arguments
clap = { version = "4.5.26", features = ["derive"] }

# Configuration
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"

# Async runtime
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }

# API
url = { version = "2.5.4", features = ["serde"] }
prost = "0.13.4"
tonic = "0.12.3"

[build-dependencies]
toml = "0.8.19"
tonic-build = "0.12.3"