name: "atomic-cloud"
version: "${client_version}"
author: "HttpRafa"
main: "de.rafael.atomic.cloud.CloudPlugin"
folia-supported: true
description: "This plugin establishes a connection with the cloud and provides an API"
api-version: "1.21"
bootstrapper: "de.rafael.atomic.cloud.CloudPluginBootstrap"
loader: "de.rafael.atomic.cloud.CloudPluginLoader"