name: "ac-notify"
version: "${client_version}"
author: "HttpRafa"
main: "io.atomic.cloud.paper.notify.NotifyPlugin"
folia-supported: true
description: "This plugin provides a way to see when servers start or stop"
api-version: "1.21"
bootstrapper: "io.atomic.cloud.paper.notify.NotifyPluginBootstrap"
dependencies:
  bootstrap:
    ac-core:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    ac-core:
      load: BEFORE
      required: true
      join-classpath: true