name: "atomic-cloud"
version: "0.1.0"
main: "de.rafael.atomic.cloud.CloudPlugin"
description: "This plugin establishes a connection with the cloud and provides an API"
api-version: "1.21"
bootstrapper: "de.rafael.atomic.cloud.CloudPluginBootstrapper"
loader: "de.rafael.atomic.cloud.CloudPluginLoader"