[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
# Common
common = { path = "../../common" }

# Logging
log = "0.4.22"
simplelog = "0.12.2"
colored = "2.1.0"

# Error handling
anyhow = "1.0.86"

# Signal handling
ctrlc = "3.4.4"

# User system
uuid = { version = "1.10.0", features = ["v4"] }

# Command line arguments
clap = { version = "4.5.11", features = ["derive"] }

# Regex parsing
regex = "1.10.5"

# Async runtime
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "macros", "process"] }

# API
url = "2.5.2"
prost = "0.13.1"
tonic = "0.12.1"

[build-dependencies]
toml = "0.8.16"
tonic-build = "0.12.1"