[package]
name = "wrapper"
version = "0.0.0-nightly"
edition = "2021"

[dependencies]
# Common
common = { path = "../../common" }

# Logging
simplelog = { version = "0.12.2", features = ["paris"] }

# Error handling
anyhow = "1.0.96"

# Signal handling
ctrlc = "3.4.5"

# User system
uuid = { version = "1.15.1", features = ["v4"] }

# Command line arguments
clap = { version = "4.5.31", features = ["derive"] }

# Regex parsing
regex = "1.11.1"

# Async runtime
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "process"] }

# API
url = "2.5.4"
prost = "0.13.5"
tonic = "0.12.3"

[build-dependencies]
toml = "0.8.20"
tonic-build = "0.12.3"