[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
# Common
common = { path = "../../common" }

# Logging
log = "0.4.22"
simplelog = "0.12.2"
colored = "2.1.0"

# Error handling
anyhow = "1.0.93"

# Signal handling
ctrlc = "3.4.5"

# User system
uuid = { version = "1.11.0", features = ["v4"] }

# Command line arguments
clap = { version = "4.5.21", features = ["derive"] }

# Regex parsing
regex = "1.11.1"

# Async runtime
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros", "process"] }

# API
url = "2.5.4"
prost = "0.13.3"
tonic = "0.12.3"

[build-dependencies]
toml = "0.8.19"
tonic-build = "0.12.3"