package cloudlet:driver;

interface log {
    variant level {
        debug,
        info,
        warn,
        error,
    }
    log-string: func(level: level, message: string);
}

interface platform {
    variant os {
        unix,
        windows,
    }
    get-os: func() -> os;
}

interface http {
    variant method {
        get,
        patch,
        post,
        put,
        delete,
    }
    record header {
        key: string,
        value: string,
    }
    record response {
        status-code: u32,
        reason-phrase: string,
        headers: list<header>,
        bytes: list<u8>,
    }
    send-http-request: func(method: method, url: string, headers: list<header>, body: option<list<u8>>) -> option<response>;
}

interface process {
    variant reference {
        controller,
        configs,
        data,
    }
    variant std-reader {
        stdout,
        stderr,
    }
    record directory {
        path: string,
        reference: reference,
    }
    spawn-process: func(command: string, args: list<string>, directory: directory) -> result<u32, string>;
    kill-process: func(pid: u32) -> result<bool, string>;
    drop-process: func(pid: u32) -> result<bool, string>;

    try-wait: func(pid: u32) -> result<option<s32>, string>;

    read-line: func(pid: u32, std: std-reader) -> result<tuple<u32, string>, string>;

    read: func(pid: u32, buf-size: u32, std: std-reader) -> result<tuple<u32, list<u8>>, string>;
    read-to-end: func(pid: u32, std: std-reader) -> result<tuple<u32, list<u8>>, string>;
    write-stdin: func(pid: u32, data: list<u8>) -> result<bool, string>;
}

interface api {
    get-name: func() -> string;
}

interface bridge {
    type uuid = string;

    /* Init */
    record information {
        authors: list<string>,
        version: string,
        ready: bool,
    }

    /* Cloudlet | Start */
    record capabilities {
        memory: option<u32>,
        max-allocations: option<u32>,
        child: option<string>,
    }

    record remote-controller {
        address: string,
    }
    /* Cloudlet | End */

    /* Allocation */
    record address {
        host: string,
        port: u16,
    }

    /* Unit | Start */
    record resources {
        memory: u32,
        swap: u32,
        cpu: u32,
        io: u32,
        disk: u32,
        addresses: u32,
    }

    record setting {
        key: string,
        value: string,
    }

    variant retention {
        permanent,
        temporary,
    }

    record key-value {
        key: string,
        value: string,
    }

    record spec {
        settings: list<key-value>,
        environment: list<key-value>,
        disk-retention: retention,
        image: string,
    }

    record allocation {
        addresses: list<address>,
        resources: resources,
        spec: spec,
    }

    record auth {
        token: string,
    }

    record unit-proposal {
        name: string,
        deployment: option<string>,
        resources: resources,
        spec: spec,
    }

    record unit {
        name: string,
        uuid: uuid,
        deployment: option<string>,
        allocation: allocation,
        auth: auth,
    }
    /* Unit | End */

    resource generic-cloudlet {
        constructor(cloud-identifier: string, name: string, id: option<u32>, capabilities: capabilities, controller: remote-controller);
        allocate-addresses: func(unit: unit-proposal) -> result<list<address>, string>;
        deallocate-addresses: func(addresses: list<address>);

        start-unit: func(unit: unit);
        restart-unit: func(unit: unit);
        stop-unit: func(unit: unit);
    }

    resource generic-driver {
        constructor(cloud-identifier: string);
        init: func() -> information;
        init-cloudlet: func(name: string, capabilities: capabilities, controller: remote-controller) -> result<generic-cloudlet, string>;
    }
}

world driver {
    export bridge;
    import api;
    import log;
    import platform;
    import http;
    import process;
}