package plugin:system;

interface types {
    type error-message = string;
    type scoped-errors = list<scoped-error>;

    record scoped-error {
        scope: string,
        message: error-message,
    }

    variant reference {
        controller,
        configs,
        data,
    }

    record directory {
        path: string,
        reference: reference,
    }
}

interface data-types {
    type uuid = string;

    flags features {
        node,
        listener,
    }

    record information {
        authors: list<string>,
        version: string,
        features: features,
        ready: bool,
    }

    record capabilities {
        memory: option<u32>,
        max-servers: option<u32>,
        child: option<string>,
    }

    record address {
        host: string,
        port: u16,
    }

    record resources {
        memory: u32,
        swap: u32,
        cpu: u32,
        io: u32,
        disk: u32,
        ports: u32,
    }

    record setting {
        key: string,
        value: string,
    }

    variant disk-retention {
        permanent,
        temporary,
    }

    record specification {
        settings: list<tuple<string, string>>,
        environment: list<tuple<string, string>>,
        disk-retention: disk-retention,
        image: string,
    }

    record allocation {
        ports: list<address>,
        resources: resources,
        specification: specification,
    }

    record server-proposal {
        name: string,
        group: option<string>,
        resources: resources,
        specification: specification,
    }

    record server {
        name: string,
        uuid: uuid,
        group: option<string>,
        allocation: allocation,
        token: string,
    }
}

interface log {
    variant level {
        debug,
        info,
        warn,
        error,
    }
    log-string: func(level: level, message: string);
}

interface platform {
    variant os {
        unix,
        windows,
    }
    get-os: func() -> os;
}

interface tls {
    get-certificate: func() -> option<string>;
}

interface file {
    use types.{error-message, directory};
    remove-dir-all: func(directory: directory) -> result<_, error-message>;
}

interface http {
    variant method {
        get,
        patch,
        post,
        put,
        delete,
    }

    record header {
        key: string,
        value: string,
    }

    record response {
        status-code: u32,
        reason-phrase: string,
        headers: list<header>,
        bytes: list<u8>,
    }

    send-http-request: func(method: method, url: string, headers: list<header>, body: option<list<u8>>) -> option<response>;
}

interface screen {
    use types.{error-message};

    variant screen-type {
        unsupported,
        supported(screen),
    }

    resource screen {
        pull: func() -> result<list<string>, error-message>;
        write: func(data: list<u8>) -> result<_, error-message>;
    }
}

interface process {
    use types.{error-message, directory};

    variant exit-status {
        code(s32),
        signal(s32),
        unknown,
    }

    resource process-builder {
        constructor(command: string);

        args: func(args: list<string>);
        environment: func(environment: list<tuple<string, string>>);
        directory: func(directory: directory);
        spawn: func() -> result<process, error-message>;
    }

    resource process {
        kill: func() -> result<_, error-message>;
        try-wait: func() -> result<option<exit-status>, error-message>;

        read-lines: func() -> list<string>;
        write-all: func(data: list<u8>) -> result<_, error-message>;
        flush: func() -> result<_, error-message>;
    }
}

interface guard {
    resource guard {}
}

interface event {
    use types.{error-message};
    use data-types.{server};

    flags events {
        server-start,
        server-stop,
    }

    resource listener {
        server-start: func(server: server) -> result<_, error-message>;
        server-stop: func(server: server) -> result<_, error-message>;
    }
}

interface bridge {
    use types.{error-message, scoped-errors};
    use data-types.{information, capabilities, address, server-proposal, server};
    use screen.{screen-type};
    use guard.{guard};
    use event.{events, listener};

    resource node {
        tick: func() -> result<_, scoped-errors>;
        allocate: func(server: server-proposal) -> result<list<address>, error-message>;
        free: func(addresses: list<address>);
        start: func(server: server) -> screen-type;
        restart: func(server: server);
        stop: func(server: server, guard: guard);
    }

    resource plugin {
        constructor(cloud-identifier: string);
        init: func() -> information;
        init-listener: func() -> tuple<events, listener>;
        init-node: func(name: string, capabilities: capabilities, controller: string) -> result<node, error-message>;
        tick: func() -> result<_, scoped-errors>;
        shutdown: func() -> result<_, scoped-errors>;
    }
}

world plugin {
    export bridge;
    export screen;
    export event;
    import guard;
    import log;
    import platform;
    import tls;
    import file;
    import http;
    import process;
}