description = "Paper is a Minecraft game server based on Spigot, designed to greatly improve performance and offer more advanced features and API"
version = "0.1.0"
authors = ["HttpRafa"]

exclusions = ["template.toml", "prepare/"]

[prepare.unix]
command = "bash"
args = ["-c", "chmod +x prepare/unix.sh && ./prepare/unix.sh"]

[prepare.windows]
command = "powershell.exe"
args = ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "prepare/windows.ps1"]

[startup.unix]
command = "echo"
args = ["Hello, World!"]

[startup.windows]
command = "echo"
args = ["Hello, World!"]