description = "Paper is a Minecraft game server based on Spigot, designed to greatly improve performance and offer more advanced features and API"
version = "0.1.0"
authors = ["HttpRafa"]

[prepare.unix]
command = "bash"
args = ["-c", "chmod +x prepare/unix.sh && ./prepare/unix.sh"]

[prepare.windows]
command = "prepare\\windows.bat"
args = []

[startup.unix]
command = "echo"
args = ["Hello, World!"]

[startup.windows]
command = "echo"
args = ["Hello, World!"]