[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
log = "0.4.22"
simplelog = "0.12.2"
colored = "2.2.0"

# Command line arguments
clap = { version = "4.5.23", features = ["derive"] }