[package]
name = "common"
version = "0.2.0"
edition = "2021"

[dependencies]
# Logging
simplelog = { version = "0.12.2", features = ["paris"] }
colored = "2.2.0"

# Error handling
anyhow = "1.0.93"

# Command line arguments
clap = { version = "4.5.23", features = ["derive"] }

# Configuration
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"