package node:driver;

interface log {
    linfo: func(message: string);
    lwarn: func(message: string);
    lerror: func(message: string);
    ldebug: func(message: string);
}

interface api {
    get-name: func() -> string;
}

interface bridge {
    record information {
        authors: list<string>,
        version: string,
    }

    init: func() -> information;
}

world driver {
    export bridge;
    import api;
    import log;
}