package node:driver;

interface log {
    info: func(message: string);
    warn: func(message: string);
    error: func(message: string);
    debug: func(message: string);
}

interface api {
    get-name: func() -> string;
}

interface bridge {
    record information {
        authors: list<string>,
        version: string,
    }

    init: func() -> information;
}

world driver {
    export bridge;
    import api;
    import log;
}