# This configuration is crucial for granting the plugins their required permissions
# https://httprafa.github.io/atomic-cloud/plugins/wasm/permissions/

[[plugins]]
name = "local"
permissions = "ALLOW_PROCESS | ALLOW_REMOVE_DIR_ALL"
mounts = []

[[plugins]]
name = "pelican"
permissions = "INHERIT_NETWORK | ALLOW_IP_NAME_LOOKUP | ALLOW_HTTP"
mounts = []

[[plugins]]
name = "cloudflare"
permissions = "INHERIT_NETWORK | ALLOW_IP_NAME_LOOKUP | ALLOW_HTTP"
mounts = []