# This configuration is crucial for granting the plugins their required permissions
# https://httprafa.github.io/atomic-cloud/plugins/wasm/permissions/

[[plugins]]
name = "local"
inherit_stdio = false
inherit_args = false
inherit_env = false
inherit_network = false
allow_ip_name_lookup = false
allow_http = false
allow_process = true
allow_remove_dir_all = true
mounts = []

[[plugins]]
name = "pelican"
inherit_stdio = false
inherit_args = false
inherit_env = false
inherit_network = true
allow_ip_name_lookup = true
allow_http = true
allow_process = false
allow_remove_dir_all = false
mounts = []