use cli::Cli;
use common::init::CloudInit;

mod cli;

// Include the build information generated by build.rs
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

pub const AUTHORS: [&str; 1] = ["HttpRafa"];

#[tokio::main]
async fn main() {
    CloudInit::init_logging();
    CloudInit::print_ascii_art("Atomic Cloud CLI", &VERSION, &AUTHORS);

    let mut cli = Cli::new().await;
    cli.start().await;
}
