#![warn(clippy::all, clippy::pedantic)]

use application::Cli;
use eyre::Result;

mod application;

// Include the build information generated by build.rs
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

pub const AUTHORS: [&str; 1] = ["HttpRafa"];

#[tokio::main]
async fn main() -> Result<()> {
    eyre::install()?;
    let terminal = ratatui::init();
    let result = Cli::new().run(terminal).await;
    ratatui::restore();
    result
}
