name: Docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Deploy Docs
        run: mkdocs gh-deploy --force