on:
  push:
    branches:
      - main
    paths:
      - clients/jvm/paper/**
name: Publish paper plugin

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build plugin
        working-directory: clients/jvm
        run: |
          chmod +x gradlew
          ./gradlew paper:build
        env:
          CURRENT_COMMIT: ${{ steps.commit.outputs.short }}
          CURRENT_BUILD: ${{ github.run_number }}

      - name: Copy jar file
        if: success()
        run: |
          mv $(find ./clients/jvm/paper/build -name "*-all.jar") cloud-paper-client.jar

      - name: Upload file to Github
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: paper-client
          path: |
            cloud-paper-client.jar
            LICENSE