on:
  push:
    branches:
      - main
    paths:
      - clients/minecraft/jvm/paper/**
name: Publish paper plugin

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: DD-MM-YYYY-hh-mm-ss
          utcOffset: "+02:00"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build plugin
        working-directory: clients/minecraft/jvm
        run: ./gradlew paper:build

      - name: Copy jar file
        if: success()
        run: |
          mv $(find ./clients/minecraft/jvm/paper/build -name "*-all.jar") cloud-paper-client.jar

      - name: Upload file to Github
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: paper-plugin
          path: |
            cloud-paper-client.jar
            LICENSE