on:
  push:
    branches:
      - main
    paths:
      - clients/jvm/api/**
name: Publish api to maven repository

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Publish api
        working-directory: clients/jvm
        run: |
          chmod +x gradlew
          ./gradlew publish
        env:
          CURRENT_COMMIT: ${{ steps.commit.outputs.short }}
          CURRENT_BUILD: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}