name: Publish API to Maven Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - clients/jvm/api/**

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Gradle Dependencies
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle-wrapper.jar') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Publish API
        working-directory: clients/jvm
        run: |
          chmod +x gradlew
          ./gradlew publish --no-daemon
        env:
          CURRENT_COMMIT: ${{ github.sha }}
          CURRENT_BUILD: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}