on:
  push:
    branches:
      - main
    paths:
      - drivers/pterodactyl/**
name: Publish pterodactyl driver

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip1

      - name: Install wasm-tools
        run: |
          mkdir tools/
          cd tools/
          wget https://github.com/bytecodealliance/wasm-tools/releases/download/v1.209.0/wasm-tools-1.209.0-x86_64-linux.tar.gz
          tar -xvf wasm-tools-1.209.0-x86_64-linux.tar.gz
          mv wasm-tools-1.209.0-x86_64-linux/* .

      - name: Build Driver
        run: |
          export RUSTFLAGS="-Z wasi-exec-model=reactor"
          cargo +nightly build -p pterodactyl --target wasm32-wasip1 --release
          ./tools/wasm-tools component new ./target/wasm32-wasip1/release/pterodactyl.wasm \
              -o ./pterodactyl.wasm --adapt ./drivers/files/wasi_snapshot_preview1.reactor.wasm
        env:
          CURRENT_COMMIT: ${{ steps.commit.outputs.short }}
          CURRENT_BUILD: ${{ github.run_number }}

      - name: Upload file to Github
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pterodactyl
          path: |
            pterodactyl.wasm
            LICENSE