on:
  push:
    paths:
      - controller/**
      - clients/wrapper/**
      - drivers/pterodactyl/**
name: Clippy check

jobs:
  clippy_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - name: Install Protobuf
        run: |
          sudo apt update
          sudo apt install protobuf-compiler -y

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features