on:
  push:
    branches:
      - main
    paths:
      - controller/**
name: Publish controller

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
          - name: linux
            platform: x86_64-unknown-linux-gnu
            extension: ""
          - name: windows
            platform: x86_64-pc-windows-gnu
            extension: ".exe"
        feature:
          - name: wasm-drivers
            file-name: wasm

    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.platform }}

      - name: Install Protobuf and MinGW (for Windows build)
        run: |
          sudo apt update
          sudo apt install protobuf-compiler gcc-mingw-w64 -y

      - name: Build Controller
        run: cargo build -p controller --release --target ${{ matrix.target.platform }} --features ${{ matrix.feature.name }}
        env:
          CURRENT_COMMIT: ${{ steps.commit.outputs.short }}
          CURRENT_BUILD: ${{ github.run_number }}

      - name: Copy Executable
        if: success()
        run: |
          mv ./target/${{ matrix.target.platform }}/release/controller${{ matrix.target.extension }} controller-${{ matrix.target.name }}-${{ matrix.feature.file-name }}${{ matrix.target.extension }}

      - name: Upload file to Github
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: controller-${{ matrix.target.name }}-${{ matrix.feature.file-name }}
          path: |
            controller-${{ matrix.target.name }}-${{ matrix.feature.file-name }}${{ matrix.target.extension }}
            LICENSE