on:
  push:
    branches:
      - main
    paths:
      - controller/drivers/pelican/**
name: Publish pelican driver

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: DD-MM-YYYY-hh-mm-ss
          utcOffset: "+02:00"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip1

      - name: Install wasm-tools
        working-directory: controller/
        run: |
          mkdir tools/
          cd tools/
          wget https://github.com/bytecodealliance/wasm-tools/releases/download/v1.209.0/wasm-tools-1.209.0-x86_64-linux.tar.gz
          tar -xvf wasm-tools-1.209.0-x86_64-linux.tar.gz
          mv wasm-tools-1.209.0-x86_64-linux/* .

      - name: Build Driver
        working-directory: controller/
        run: |
          export RUSTFLAGS="-Z wasi-exec-model=reactor"
          cargo +nightly build -p pelican --target wasm32-wasip1 --release
          ./tools/wasm-tools component new ./target/wasm32-wasip1/release/pelican.wasm \
              -o ../pelican.wasm --adapt ./drivers/files/wasi_snapshot_preview1.reactor.wasm

      - name: Upload file to Github
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pelican
          path: |
            pelican.wasm
            LICENSE